# Generated by Django 4.2.2 on 2023-06-22 04:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('white', 'White'), ('red', 'Red'), ('blue', 'Blue'), ('black', 'Black'), ('yellow', 'Yellow'), ('gray', 'Gray')], max_length=50)),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('production_cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('transportation_cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
            ],
        ),
    ]
